ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerceapp.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceapp/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.utils.text import slugify
# Banner
class Banner(models.Model):
    img=models.ImageField(upload_to="banner_imgs/")
    alt_text=models.CharField(max_length=300)

    class Meta:
        verbose_name_plural='1. Banners'

    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.img.url))

    def __str__(self):
        return self.alt_text

# Category
class Category(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to="cat_imgs/")

    class Meta:
        verbose_name_plural='2. Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

# Brand
class Brand(models.Model):
    title=models.CharField(max_length=100, null=True)
    image=models.ImageField(upload_to="brand_imgs/", null=True)

    class Meta:
        verbose_name_plural='3. Brands'

    def __str__(self):
        return self.title

# Color
class Color(models.Model):
    title=models.CharField(max_length=100)
    color_code=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='4. Colors'

    def color_bg(self):
        return mark_safe('<div style="width:30px; height:30px; background-color:%s"></div>' % (self.color_code))

    def __str__(self):
        return self.title

# Size
class Size(models.Model):
    title=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='5. Sizes'

    def __str__(self):
        return self.title


# Product Model
class Product(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(null=False, editable=False, default="")
    detail=models.TextField()
    specs=models.TextField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE, null=True)
    status=models.BooleanField(default=True)
    is_featured=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='6. Products'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

# Product Attribute
class ProductAttribute(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE, null=True)
    color=models.ForeignKey(Color,on_delete=models.CASCADE, null=True)
    size=models.ForeignKey(Size,on_delete=models.CASCADE, null=True)
    price=models.PositiveIntegerField(default=0)
    image=models.ImageField(upload_to="product_imgs/",null=True)

    class Meta:
        verbose_name_plural='7. ProductAttributes'

    def __str__(self):
        return self.product.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

# Order
status_choice=(
        ('process','In Process'),
        ('shipped','Shipped'),
        ('delivered','Delivered'),
    )
# class CartOrder(models.Model):
#     user=models.ForeignKey(User,on_delete=models.CASCADE)
#     total_amt=models.FloatField()
#     paid_status=models.BooleanField(default=False)
#     order_dt=models.DateTimeField(auto_now_add=True)
#     order_status=models.CharField(choices=status_choice,default='process',max_length=150)

#     class Meta:
#         verbose_name_plural='8. Orders'

# # OrderItems
# class CartOrderItems(models.Model):
#     order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
#     invoice_no=models.CharField(max_length=150)
#     item=models.CharField(max_length=150)
#     image=models.CharField(max_length=200)
#     qty=models.IntegerField()
#     price=models.FloatField()
#     total=models.FloatField()

#     class Meta:
#         verbose_name_plural='9. Order Items'

#     def image_tag(self):
#         return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))
# #  <------- PROVISION MODELS FOR PRODUCT REVIEWS AND WISHLIST -------->

# Product Review

class CartOrderDetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.CharField(max_length=200)
    price = models.CharField(max_length=200)
    details = models.ForeignKey(ProductAttribute, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='9. Order Items'

# RATING=(
#     (1,'1'),
#     (2,'2'),
#     (3,'3'),
#     (4,'4'),
#     (5,'5'),
# )
 

# class ProductReview(models.Model):
#     user=models.ForeignKey(User,on_delete=models.CASCADE)
#     product=models.ForeignKey(Product,on_delete=models.CASCADE)
#     review_text=models.TextField()
#     review_rating=models.CharField(choices=RATING,max_length=150)

#     class Meta:
#         verbose_name_plural='Reviews'

#     def get_review_rating(self):
#         return self.review_rating

# WishList
# class Wishlist(models.Model):
#     user=models.ForeignKey(User,on_delete=models.CASCADE)
#     product=models.ForeignKey(Product,on_delete=models.CASCADE)

#     class Meta:
#         verbose_name_plural='Wishlist'

# AddressBook
class UserAddressBook(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    mobile=models.CharField(max_length=50,null=True)
    address=models.TextField()
    status=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='AddressBook'

    

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js" integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&family=Poppins:wght@300;500;700&family=Quicksand:wght@300;500;700&display=swap" rel="stylesheet">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <script src={% static '/js/customjs1.js' %}></script>
    <!-- site metas -->
    <title>{% block title %}{% endblock title %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href={% static "/css/bootstrap.min.css" %}>
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href={% static "/css/main1.css" %}>
    <link rel="stylesheet" type="text/css" href={% static "/css/product.css" %}>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href={% static '/css/responsive.css' %}>
    <link rel="icon" href={% static '/images/fevicon.png' %} type="image/gif" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
        media="screen">
</head>

<body>
    <!-- banner bg main start -->
    <div class="discountsection" style="width: 100%; max-width: 100vw; padding: 10px 0; background-color: black;">
        <h3 style="color: white; text-align: center; font-size: 12px; padding: 0; font-style: oblique;">UP TO 40% OFF ON
            SELECT STYLES</h3>
    </div>
    <div class="banner_bg_mainn">
        <!-- header top section start -->
        <div class="contain">
            <div class="header_section_topbar"
                style="width: 100%;background-color: #2b2a29;height: auto;padding: 10px 0px;">
                <div class="row">
                   
                    <div class="col-sm-12">
                        <div class="custom_menu">
                            <div class="iconsWrapper" style="display:flex;align-items: center; justify-content: center;">
                                <i class="fa-solid fa-magnifying-glass"
                                style="font-size: 15px; color: white; padding: 0 10px;"></i>
                            <div class="iconsbar" id="iconsbar">
                                
                                <i class="fa-solid fa-cart-shopping"
                                    style="font-size: 15px; color: white; padding: 0 10px; position: relative;"><div class="cart-length" style="border-radius: 100%; background-color: black; color: white; font-size: 12px; font-family: sans-serif; position: absolute; bottom: -3px; right: 0px; padding: 2px; font-weight: 500;"><span class="cart-list">{{cart_length}}</span></div></i>
                                <img src="/static/india.png" alt="flag"
                                    style="height: 20px; width: 50px; padding: 0 10px; border-radius: 20%;">
                                    {% if user.is_authenticated %}
                                    <h3 style="color: white; font-size: 15px; padding: 0 10px;">{{user.username}}</h3>
                                    {% else %}
                                    <h3 style="color: white; font-size: 15px; padding: 0 10px;">Login</h3>
                                    {% endif %}
                            </div>
                        </div>
                            <div class="logoimage">
                                <h1 style="color: white; font-size: 20px; padding: 0;">Wigs Company</h1>
                            </div>
                            <span class="toggle_icon" onclick="openNav()"><img src="/static/images/toggle-icon.png"
                                    style="font-size:20px; height:20px; width:20px;"></span>
                        </div>
                    </div>
                </div>
            </div>
            {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
                {% endfor %}
        </ul>
        {% endif %}
        </div>

        <div class="header_section">
            <div class="container">
                <div class="containt_main">
                    <div id="mySidenav" class="sidenav">
                        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                        <a href="/">Home</a>
                        <a href="/categories/all">Categories</a>
                        <a href="/cart">Cart</a>
                        <a href="/about">About Us</a>
                        <a href="/contact">Contact</a>
                        {% if user.is_authenticated %}
                        <a href="login">{{user.username}}</a>
                        {% else %}
                        <a href="/contact">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


    </div>
    </div>

    {% block body %}{% endblock body %}

    <div class="footer_section layout_padding">
        <div class="container">
            <div class="footer_logo"><a href="index.html"><img src="images/footer-logo.png"></a></div>
            <div class="input_bt">
                <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
                <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
            </div>
            <div class="footer_menu">
                <ul>
                    <li><a href="#">Best Sellers</a></li>
                    <li><a href="#">Gift Ideas</a></li>
                    <li><a href="#">New Releases</a></li>
                    <li><a href="#">Today's Deals</a></li>
                    <li><a href="#">Customer Service</a></li>
                </ul>
            </div>
            <div class="location_main">Help Line Number : <a href="#">+1 1800 1200 1200</a></div>
        </div>
    </div>
    <!-- footer section end -->
    <!-- copyright section start -->
    <div class="copyright_section">
        <div class="container">
            <p class="copyright_text">© 2020 All Rights Reserved. Design by <a href="https://html.design">Free html
                    Templates</a></p>
        </div>
    </div>
    <!-- copyright section end -->
    <!-- Javascript files-->
    <script src="js/jquery.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/jquery-3.0.0.min.js"></script>
    <script src="js/plugin.js"></script>
    <!-- sidebar -->
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="js/custom.js"></script>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>
</body>

</html>

templates/cart.html
{% extends 'base.html' %}
{% block title %}{{user.username}}'s Shoopping Cart{% endblock title %}
{% block body %}
<div class="container">
    {% load static %}
    <div class="heading">
        <h1
            style="text-align:center; font-size: 28px; font-family: poppins, sans-serif; font-weight: 500; padding: 20px 0px; color:#f53163">
            My Shopping Cart</h1>
    </div>
    <div class="cart-wrapper" style="padding: 20px 0px; background-color: white; border-radius: 20px; margin:20px 0px;">
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th scope="col">Description</th>
                    <th scope="col">Size</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Remove</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                <tr>
                    <td>
                        <div class="desc-wrapper" style="display: flex;">
                            <img src="/media/{{item.details.image}}" alt="product_image"
                                style="height: 100px; width: 100px; margin-right: 10px;">
                            <div class="description"
                                style="display: flex; flex-direction: column; justify-content: center; margin-left: 10px;">
                                <h1
                                    style="font-size: 16px; font-family: poppins, sans-serif; font-weight: 500; color: black; padding-bottom: 6px;">
                                    {{item.product.title}}</h1>
                                <h3
                                    style="font-size: 12px; font-family: poppins, sans-serif; font-weight: 300; color: black;">
                                    {{item.details.color.title}}</h3>
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="size-details">
                            <div class=" size-box"
                            style="background-color: white;color: black;height: 2.2rem;border: 2px solid #dbdbdb;width: 2rem;display: flex;align-items: center;justify-content: center;text-align: center;">
                            <p>16''</p>
                        </div>
                </div>
                </td>
                <td>
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-secondary">+</button>
            <input type="text" value='{{item.qty}}' style="width: 35px; text-align: center; font-size: 16px;" disabled>
            <button type="button" class="btn btn-secondary">-</button>
        </div>
    </td>
    <td>
        <div class="delete" style="text-align: center;">
            <i class="fa-solid fa-trash" style="font-size: 25px; color: red;"></i>
        </div>
    </td>
    <td>
        <div class="price" style="text-align: center;">
            <h3 style="font-size: 16px; font-weight: 500; font-family: poppins, sans-serif;">${{item.price}}</h3>
        </div>
    </td>
    </tr>
    {% endfor %}
    
    </tbody>
    </table>

    <div class="checkout-section row">
        <div class="promo-code-section col-8" style="display: flex;">
            <input type="text" name="promo_code" placeholder='Please enter your promo code here' style="width: 100%; font-size: 14px; font-weight: 500; font-family: poppins, sans-serif; padding: 5px 10px; outline: none; border: 2px solid rgb(176, 176, 176);"><input type="submit" value="Apply discount" style="margin: 0px -50px; outline: none; border: none; color: white; background-color: #B6666F; cursor:pointer; width:12rem; text-align: left; padding-left: 10px;">
        </div>
        <div class="col-4">
            <button style="width: 100%; padding: 10px 10px; background-color: black; color: white;">Checkout &#x2192;</button>
        </div>
    </div>
</div>
</div>
{% endblock body %}

templates/category.html
{% extends 'base.html' %}
{% block title %}Category Page{% endblock title %}
{% block body %}
{% load static %}
<div class="headersection">
    <h1 class="py-4 px-2 text-center">Curly Wigs</h1>
</div>
<div class="productsection row" style="padding: 0 30px">
    {% for prod in data %}
    <div class="productBox col-md" style="cursor:pointer">
        <a href="http://localhost:8000/product/{{prod.slug}}">
        <div class="image-wrapper" style="position: relative;">
            <img src="/media/{{prod.productattribute_set.first.image}}" alt="product1">
        </div>
        <div class="title py-2" style="width:100%;font-size: 20px; color: rgb(40, 40, 40);">{{prod.title}}</div>
            <div class="price" style="width:100%; margin: 0;">
                <p  style="color: rgb(211, 141, 37); font-size: 20px; margin: 0;">Rs.{{prod.productattribute_set.first.price}}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock body %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wiggs - Best Quality Wiggss</title>
</head>
<body>
    
</body>
</html>

templates/product.html
{% extends 'base.html' %}
{% block title %}{{data.title}} | Wig Website{% endblock title %}
{% block body %}
<style>
    .buy-btn1 button:hover {
        background-color: black;
        color: white;
        border: 2px solid white
    }

    .buy-btn1 button {
        background-color: black;
        color: white;
        border: 2px solid black;
    }

    .foccused {
        border: 1px solid cyan;
    }
</style>
<div class="container">
    <div class="row product-wrapper py-5 px-md-3 px-lg-5">
        <div class="col-md-6">
            <div class="image">
                <img src="/media/{{data.productattribute_set.first.image}}" alt="product">
            </div>
        </div>
        <div class="col-md-6">
            <div class="details">
                <div class="title">
                    <h1 class="px-md-3 py-4"
                        style="font-family: poppins, sans-serif; font-weight: 900; font-size: 18px;">{{data.title}}</h1>
                </div>
                <div class="specs row">
                    <div class="col-6">
                        <div class="price-section" style="display: flex;">
                            <h3 class="px-md-3 product-price-{{data.id}}  product-price"
                                style="font-size:22px; margin-right: 10px; color: black; font-family: poppins, sans-serif; font-weight: 500;">
                                </h3>
                            <h3 
                                style="font-size:16px; text-decoration: line-through; color: black; font-family: poppins, sans-serif; font-weight: 500;">
                                $800</h3>
                        </div>

                    </div>
                    <div class="col-6">
                        <h3 class="px-md-3"
                            style="font-size:18px; color: #F53163; font-family: poppins, sans-serif; font-weight: 500; text-align: right;">
                            25% OFF</h3>
                    </div>
                </div>
                <div class="options-wrapper my-4 mx-md-3">
                    <div class="optionsSection" 
                        style="cursor:pointer; border-bottom: 2px solid #F53163; margin: 20px 0px; transition: all 200ms;">
                        <div class="color-select row" id="colorOptionSelect">
                            <div class="text col-3">
                                <h3 style="font-size: 16px; font-family: poppins, sans-serif; font-weight: 300;">COLOR
                                </h3>
                            </div>
                            <div class="color-name col-7">
                                <div class="color-options"
                                    style="display: flex; align-items: center; justify-content: center;">
                                    <div class="color-box" 
                                        style="height:20px; display: flex; flex-direction: column; align-items: center; justify-content: center; width: 20px; transform: rotate(45deg); background-color: {{colors.0.color__color_code}}; margin: 0px 10px; margin-bottom: 10px;">
                                    </div>
                                    <div class="color-name">
                                        <h3 class="color-text"
                                            style=" text-transform: capitalize; font-size: 16px; font-family: poppins, sans-serif;">
                                            {{colors.0.color__title}}</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="arrow-down col-2" id="arrow-down">
                                <i style="font-size: 20px; color: #F53163;" class="fa-solid fa-caret-down"></i>
                            </div>
                            <div class="arrow-up col-2 d-none" id="arrow-up">
                                <i style="font-size: 20px; color: #F53163;" class="fa-solid fa-caret-up"></i>
                            </div>
                        </div>
                        <div class="postselection-row py-2 d-none" id="postcolorselect" style="display: flex;">
                            {% for clr in colors %}
                            <div class="box ml-3 choose-color" data-color="{{clr.color__id}}" data-color-code="{{clr.color__color_code}}" data-color-text="{{clr.color__title}}"
                                style="height:30px; display: flex; flex-direction: column; align-items: center; justify-content: center; width: 30px; transform: rotate(45deg); background-color: {{clr.color__color_code}}; margin: 0px 10px; margin-bottom: 10px; cursor:pointer">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <h1 class="slug-h1 d-none">{{data.slug}}</h1>
                    <div class="optionsSection" style="border-bottom: 2px solid #F53163; margin: 20px 0px;">
                        <div class="length-select row" style="cursor:pointer">
                            <div class="text col-3">
                                <h3 style="font-size: 16px; font-family: poppins, sans-serif; font-weight: 300;">LENGTH
                                </h3>
                            </div>
                            <div class="length-name col-7">
                                <div class="length-options"
                                    style="display: flex; align-items: center; justify-content: center;">
                                    <div class="length-default" style="cursor:pointer">
                                        <h3 class="choose-sizes-default" data-size-id = "{{sizes.0.size__id}}"
                                            style=" text-transform: capitalize; font-size: 16px; font-family: poppins, sans-serif; text-align: left;">
                                            {{sizes.0.size__title}}</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="arrow col-2">
                                <i style="font-size: 20px; color: #F53163;" class="fa-solid fa-caret-down"></i>
                            </div>
                        </div>
                        <div class="length-options-name d-none" style="cursor:pointer">
                            {% for size in sizes %}
                            <h3 class="choose-size color{{size.color__id}}" data-price="{{size.price}}" data-selected-length="{{size.size__title}}" data-length-id = "{{size.size__id}}"
                                style=" text-transform: capitalize; font-size: 16px; font-family: poppins, sans-serif; text-align: left;">
                                {{size.size__title}}</h3>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="optionsSection" style="border-bottom: 2px solid #F53163; margin: 20px 0px;">
                        <div class="length-select row">
                            <div class="text col-3">
                                <h3 style="font-size: 16px; font-family: poppins, sans-serif; font-weight: 300;">QTY.
                                </h3>
                            </div>
                            <div class="length-name col-7">
                                <div class="length-options"
                                    style="display: flex; align-items: center; justify-content: center;">
                                    <div class="length-name">
                                        <h3
                                            style=" text-transform: capitalize; font-size: 16px; font-family: poppins, sans-serif; text-align: left;">
                                            1</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="arrow col-2">
                                <i style="font-size: 20px; color: #F53163;" class="fa-solid fa-caret-down"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="buy-btn1">
                    <input type="hidden" value="1" class="form-control product-qty-{{data.id}}" id="productQty" />
                    <input type="hidden" class="product-image-{{data.id}}" value="{{data.productattribute_set.first.image}}" />
                    <input type="hidden" class="product-id-{{data.id}}" value="{{data.id}}" />
                    <input type="hidden" class="product-title-{{data.id}}" value="{{data.title}}" />
                    <button class="mx-md-3 add-to-cart" data-index="{{data.id}}" id="addToCartBtn"
                        style="width: 100%; padding: 10px 10px;  text-transform: uppercase; font-family: poppins, sans-serif; font-weight: 500; text-align: center; font-size: 16px; margin: 20px 0px;">Add
                        to Cart</button>
                </div>

                <div class="desc">
                    <p class="px-md-3 m-0"
                        style="font-size: 14px; color: rgb(34, 35, 41); font-family: Quicksand, sans-serif; font-weight: 500;">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae quis, deleniti perspiciatis quas
                        ab incidunt tenetur natus sapiente architecto, saepe cum autem distinctio magnam, optio neque.
                        Atque repellat rerum cupiditate quasi! Eligendi obcaecati molestiae, cum inventore fugit
                        distinctio saepe ea assumenda error delectus incidunt odio? Magni optio perspiciatis fugit ea
                    </p>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById('colorOptionSelect').onclick = () => {
            document.getElementById('postcolorselect').classList.toggle('d-none')
            document.getElementById('arrow-up').classList.toggle('d-block')
            document.getElementById('arrow-down').classList.toggle('d-none')
        }




    </script>
</div>
{% endblock body %}